[package]
name = "hmac"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "hmac"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
hmac = "0.12.1"
sha2 = " 0.10.2"
hex = "0.4.3"